on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm build
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html # needed because of dynamic routes
      - name: Deploy
        run: | 
          cd dist
          git init
          git remote add origin https://codeberg.org/vloddot/jolt
          git checkout -b pages
          git add --all
          git commit -am 'Pages Updates' && git push -u origin pages
